#Dockerfile per Host Ubuntu

FROM ubuntu:latest

LABEL maintainer emme "emmamelluso@gmail.com"

RUN apt-get update && apt-get install -y \
bridge-utils \
net-tools \
iputils-ping \
nmap

CMD echo "Ubuntu Host"
