#Dockerfile per Host Ubuntu

FROM ubuntu:latest

LABEL maintainer emme "emmamelluso@gmail.com"

RUN apt-get update && apt-get install -y \
bridge-utils \
net-tools \
iputils-ping \
nmap \
hping3 \
ftp \
wget

CMD echo "Ubuntu Host"
