version: '2'
services:
  cliente1:
    image: 'emmame/simpleubuntu:latest'
    container_name: c1-esterno
    stdin_open: true
    privileged: true
    command: bash -c "route add default gw f1-esterno && bash"
    tty: true
    networks:
      net-esterna:
        ipv4_address: 192.1.1.2
  firewall1:
    image: 'emmame/firewall_ulogd2:latest'
    container_name: f1-esterno
    stdin_open: true
    privileged: true
    command: bash -c "service ulogd2 restart && bash"
    sysctls:
        - net.ipv4.ip_forward=1
    tty: true
    networks:
      net-dmz:
        ipv4_address: 192.1.2.5
      net-esterna:
        ipv4_address: 192.1.1.5
  webserver:
    image: 'linode/lamp:latest'
    stdin_open: true
    privileged: true
    ports:
            - '80:80/tcp'
            - '443:443/tcp'
    container_name: webserver1
    tty: true
    command: bash -c "service apache2 start && route add 192.1.1.2 gw f1-esterno && route add 192.1.3.2 gw f2-interno && bash"
    networks:
      net-dmz:
        ipv4_address: 192.1.2.2
  hostint1:
    image: 'emmame/simpleubuntu:latest'
    container_name: h1-interno
    privileged: true
    stdin_open: true
    command: bash -c "route add default gw f2-interno && bash"
    tty: true
    networks:
      net-interna:
        ipv4_address: 192.1.3.2
  firewall2:
    image: 'emmame/firewall_ulogd2:latest'
    container_name: f2-interno
    stdin_open: true
    privileged: true
    command: bash -c "service ulogd2 restart && bash"
    sysctls:
       - net.ipv4.ip_forward=1
    tty: true
    networks:
      net-dmz:
        ipv4_address: 192.1.2.6
      net-interna:
        ipv4_address: 192.1.3.6
networks:
  net-esterna:
    ipam:
      config:
        - subnet: 192.1.1.1/24
  net-dmz:
    ipam:
      config:
        - subnet: 192.1.2.1/24
  net-interna:
    ipam:
      config:
        - subnet: 192.1.3.1/24
