version: '2'
services:
  cliente1:
    image: 'emmame/simpleubuntu:latest'
    container_name: c1-esterno
    stdin_open: true
    privileged: true
    command: bash -c "route add default gw f1-esterno && bash"
    tty: true
    networks:
      net-esterna:
        ipv4_address: 192.2.1.2
  firewall1:
    image: 'emmame/firewall_ulogd2:latest'
    stdin_open: true
    container_name: f1-esterno
    tty: true
    privileged: true
    command: bash -c "route add default gw f2-interno && service ulogd2 restart && bash"
    sysctls:
        - net.ipv4.ip_forward=1
    networks:
      net-esterna:
        ipv4_address: 192.2.1.5
      net-dmz:
        ipv4_address: 192.2.2.5
      net-intermedia:
        ipv4_address: 192.2.4.5
  webserver:
    image: 'linode/lamp:latest'
    container_name: webserver1
    stdin_open: true
    privileged: true
    ports:
        - '80:80/tcp'
        - '443:443/tcp'
    tty: true
    command: bash -c "service apache2 start && route add default gw f1-esterno && bash"
    networks:
      net-dmz:
        ipv4_address: 192.2.2.2
  firewall2:
    image: 'emmame/firewall_ulogd2:latest'
    container_name: f2-interno
    stdin_open: true
    tty: true
    privileged: true
    command: bash -c "route add default gw f1-esterno && service ulogd2 restart && bash"
    sysctls:
       - net.ipv4.ip_forward=1
    networks:
      net-intermedia:
        ipv4_address: 192.2.4.6
      net-interna:
        ipv4_address: 192.2.3.6
  hostint1:
    image: 'emmame/simpleubuntu:latest'
    container_name: h1-interno
    stdin_open: true
    privileged: true
    tty: true
    command: bash -c "route add default gw f2-interno && bash"
    networks:
      net-interna:
        ipv4_address: 192.2.3.2
networks:
  net-esterna:
    ipam:
      config:
        - subnet: 192.2.1.1/24
  net-dmz:
    ipam:
      config:
        - subnet: 192.2.2.1/24
  net-intermedia:
    ipam:
      config:
        - subnet: 192.2.4.1/24
  net-interna:
    ipam:
      config:
        - subnet: 192.2.3.1/24
